global:
  scrape_interval:     15s
  evaluation_interval: 15s

  # Attach these labels to any time series or alerts when communicating with
  # external systems (federation, remote storage, Alertmanager).
  external_labels:
      monitor: 'docker-host-alpha'

# Load and evaluate rules in this file every 'evaluation_interval' seconds.
rule_files:
  - "alert.rules"

# A scrape configuration containing exactly one endpoint to scrape.
scrape_configs: 
  - job_name: 'node-1'
    scrape_interval: 5s
    static_configs:
            - targets: ['157.119.205.53:9100']
  - job_name: 'node-2'
    scrape_interval: 5s
    static_configs:
            - targets: ['103.72.223.143:9100']
  - job_name: 'node-3'
    scrape_interval: 5s
    static_configs:
            - targets: ['103.164.161.254:9100']
